@api_HostAddress = http://localhost:5054

GET {{api_HostAddress}}/musics

GET {{api_HostAddress}}/musics/73a4db77-bc6b-49e5-b6cb-c1a03110ecef

POST {{{{api_HostAddress}}}}/games
Content-Type: application/json

PUT {{{{api_HostAddress}}}}/games
Content-Type: application/json